export const FORWARDED_ONSHAPE_EVENTS = {
  ELEMENT_LOAD_DONE: "ELEMENT_LOAD_DONE",
  CHANGE_ELEMENT_TOOLBAR: "CHANGE_ELEMENT_TOOLBAR",
  ELEMENT_TOOLBAR_SET_CURRENT_TOOL: "ELEMENT_TOOLBAR_SET_CURRENT_TOOL",
  ELEMENT_TOOLBAR_EXIT_CURRENT_TOOL: "ELEMENT_TOOLBAR_EXIT_CURRENT_TOOL",
  DOCUMENT_UNLOADED: "DOCUMENT_UNLOADED",
  OPEN_MINI_TOOLBAR: "OPEN_MINI_TOOLBAR",
}

export const ACCEPTED_ONSHAPE_TO_EXTENSION_EVENT_TYPE = "OS_ANGULAR_EVENT"